name: webmat
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - seaborn
  - matplotlib
  - sympy
  - pandas
  - scipy
  - plotly
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - pip:
    - handcalcs
